name: LuaInMinecraftBukkitII
version: '${version}'
main: org.eu.smileyik.luaInMinecraftBukkitII.LuaInMinecraftBukkit
authors: [ SmileYik ]
commands:
  LuaInMinecraftBukkitII:
    aliases:
      - lua
      - limb
      - limb2