name: LuaInMinecraftBukkitII
version: '${version}'
main: org.eu.smileyik.luaInMinecraftBukkitII.LuaInMinecraftBukkit
api-version: 1.18
folia-supported: ${foliaSupported}
authors: [ SmileYik ]
commands:
  LuaInMinecraftBukkitII:
    aliases:
      - lua
      - limb
      - limb2
  Luacage: {}